# walrus-testnet-client-config.yaml
contexts:
  testnet:
    system_object: 0x6c2547cbbc38025cf3adac45f63cb0a8d12ecf777cdc75a4971612bf97fdf6af
    staking_object: 0xbe46180321c30aab2f8b3501e24048377287fa708018a5b7c2792b35fe339ee3
    exchange_objects:
      - 0xf4d164ea2def5fe07dc573992a029e010dba09b1a8dcbc44c5c2e79567f39073
      # ...more exchange objects if needed
    wallet_config:
      active_env: testnet
    rpc_urls:
      - https://fullnode.testnet.sui.io:443
default_context: testnet
